services:
  app:
    image: aurel126/minecraft-ollama-bot:latest
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
      minecraft:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: |
      /bin/sh -c "
      /bin/ollama serve &
      sleep 3 &&
      /usr/bin/ollama pull sweaterdog/andy-4:micro-q8_0 &&
      /usr/bin/ollama pull embeddinggemma &&
      tail -f /dev/null
      "
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - "25566:25566"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "1.20.2"
      MEMORY: "2G"
      ONLINE_MODE: "FALSE"
      SERVER_PORT: "25566"
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  viaproxy:
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy

volumes:
  ollama_data:

